# Generated by Django 5.2.4 on 2025-07-07 16:29

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HealthCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HealthSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8)),
                ('condition', models.CharField(choices=[('Normal', 'Normal'), ('Severe', 'Severe')], max_length=10)),
                ('status', models.CharField(choices=[('Alive', 'Alive'), ('Dead', 'Dead')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sheha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Sheha', 'Sheha'), ('Doctor', 'Doctor'), ('HealthSupervisor', 'HealthSupervisor')], max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.ForeignKey(limit_choices_to={'Doctor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casereport',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crsapp.doctor'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='health_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crsapp.healthcenter'),
        ),
        migrations.AddField(
            model_name='casereport',
            name='health_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crsapp.healthcenter'),
        ),
        migrations.AddField(
            model_name='healthsupervisor',
            name='user',
            field=models.ForeignKey(limit_choices_to={'HealthSupervisor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casereport',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crsapp.patient'),
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crsapp.region'),
        ),
        migrations.AddField(
            model_name='sheha',
            name='user',
            field=models.ForeignKey(limit_choices_to={'Sheha'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='street',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crsapp.district'),
        ),
        migrations.AddField(
            model_name='sheha',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crsapp.street'),
        ),
        migrations.AddField(
            model_name='patient',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crsapp.street'),
        ),
        migrations.AddField(
            model_name='healthcenter',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crsapp.street'),
        ),
    ]
