# Generated by Django 5.2.4 on 2025-07-14 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crsapp', '0003_patient_created_at_patient_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'Doctor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('Recovered', 'Recovered'), ('Dead', 'Dead'), ('Alive', 'Alive')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='casereport',
            unique_together={('patient',)},
        ),
    ]
