# Generated by Django 5.2.4 on 2025-07-14 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crsapp', '0004_alter_doctor_user_alter_patient_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheha',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'Sheha'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='HealthSupervisor',
        ),
    ]
