# Generated by Django 5.2.4 on 2025-07-16 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crsapp', '0005_alter_sheha_user_delete_healthsupervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casereport',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casereport', to='crsapp.doctor'),
        ),
        migrations.AlterField(
            model_name='casereport',
            name='health_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casereport', to='crsapp.healthcenter'),
        ),
        migrations.AlterField(
            model_name='casereport',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casereport', to='crsapp.patient'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
